const ActionTypes = {
    GET_ACTIVE_COURT: 'GET_ACTIVE_COURT',
    SET_ACTIVE_COURT: 'SET_ACTIVE_COURT',

    ADD_COURTS: 'ADD_COURTS',
    FILTER_COURTS: 'FILTER_COURTS',

    UPDATE_FILTERS: 'UPDATE_FILTERS',

    SET_USER_LOCATION: 'SET_USER_LOCATION'
}

export default ActionTypes;